openapi: '3.0.3'
info:
  title: GameSync API
  version: '1.0'
servers:
  - url: https://gamesync-vui5.onrender.com
paths:
  /:
    get:
      responses:
        '200':
          description: Basic Information about the Api.
  /users:
    get:
      responses:
        '200':
          description: Returns an Array of the usernames of all the users on the Platform.
  /games:
    get:
      responses:
        '200':
          description: Returns an Array of the all the games on the platform.
  

  /health:
    get:
      responses:
        '200':
          description: OK
